# Generated by Django 2.2.12 on 2021-05-05 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=1024)),
                ('content', models.TextField()),
                ('reference', models.CharField(max_length=128)),
                ('img', models.ImageField(upload_to='')),
                ('fileref', models.FileField(upload_to='')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('totalread', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='contactmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=64)),
                ('subject', models.CharField(max_length=64)),
                ('desc', models.CharField(max_length=1024)),
                ('readed', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='maxview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postid', models.IntegerField()),
                ('postview', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='refer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='tactics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='techniques',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=2048)),
                ('platform', models.CharField(max_length=128)),
                ('tactic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='temp.tactics')),
            ],
        ),
    ]
