# Generated by Django 2.2.14 on 2021-02-13 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=64)),
                ('subject', models.CharField(max_length=64)),
                ('desc', models.CharField(max_length=1024)),
            ],
        ),
    ]
