# Generated by Django 2.2.14 on 2021-02-13 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('temp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact',
            new_name='contactmodel',
        ),
    ]
