# Generated by Django 2.2.12 on 2021-06-11 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temp', '0002_remove_tactic_stix'),
    ]

    operations = [
        migrations.AddField(
            model_name='tactic',
            name='stix',
            field=models.CharField(default=1, max_length=512),
            preserve_default=False,
        ),
    ]
