# Generated by Django 2.2.12 on 2021-05-21 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('temp', '0002_remove_blog_fileref'),
    ]

    operations = [
        migrations.CreateModel(
            name='mitigation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=2048)),
                ('platform', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='subtechnique',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=2048)),
                ('platform', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='technique',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=2048)),
                ('platform', models.CharField(max_length=128)),
            ],
        ),
        migrations.RenameModel(
            old_name='tactics',
            new_name='tactic',
        ),
        migrations.DeleteModel(
            name='techniques',
        ),
        migrations.AddField(
            model_name='technique',
            name='rel_tactic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='temp.tactic'),
        ),
        migrations.AddField(
            model_name='technique',
            name='rel_technique',
            field=models.ManyToManyField(to='temp.mitigation'),
        ),
        migrations.AddField(
            model_name='subtechnique',
            name='rel_technique',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='temp.technique'),
        ),
    ]
