# Generated by Django 2.2.12 on 2021-05-21 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('temp', '0003_auto_20210521_1708'),
    ]

    operations = [
        migrations.RenameField(
            model_name='technique',
            old_name='rel_technique',
            new_name='rel_mitigation',
        ),
    ]
