# Generated by Django 2.2.14 on 2021-02-14 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('temp', '0003_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='users',
        ),
    ]
