# Generated by Django 2.2.12 on 2021-05-21 19:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('temp', '0004_auto_20210521_1711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mitigation',
            name='platform',
        ),
        migrations.AddField(
            model_name='mitigation',
            name='reference',
            field=models.CharField(default=django.utils.timezone.now, max_length=2048),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mitigation',
            name='stix',
            field=models.CharField(default=django.utils.timezone.now, max_length=512),
            preserve_default=False,
        ),
    ]
