# Generated by Django 2.2.14 on 2021-02-17 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('temp', '0006_auto_20210217_1024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactmodel',
            old_name='Readed',
            new_name='readed',
        ),
    ]
