# Generated by Django 2.2.14 on 2021-02-20 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('temp', '0010_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
