# Generated by Django 2.2.14 on 2021-02-24 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temp', '0011_delete_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=1024)),
                ('content', models.CharField(max_length=65536)),
                ('reference', models.CharField(max_length=128)),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('totalread', models.IntegerField()),
            ],
        ),
    ]
