# Generated by Django 2.2.14 on 2021-04-28 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('temp', '0013_auto_20210224_1145'),
    ]

    operations = [
        migrations.CreateModel(
            name='tactics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='techniques',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=2048)),
                ('platform', models.CharField(max_length=128)),
                ('tactic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='temp.tactics')),
            ],
        ),
    ]
