# Generated by Django 2.2.14 on 2021-04-29 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temp', '0014_tactics_techniques'),
    ]

    operations = [
        migrations.CreateModel(
            name='maxview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postid', models.IntegerField()),
                ('postview', models.IntegerField()),
            ],
        ),
    ]
