# Generated by Django 2.2.14 on 2021-01-20 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=64)),
                ('destination', models.CharField(max_length=64)),
                ('price', models.IntegerField(max_length=64)),
            ],
        ),
    ]
